version: '3.8'

networks:
  mysql-net:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - mysql-net
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql-db-sync
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_sync:/var/lib/mysql

volumes:
  mysql_data_sync:
